### ISSUE TITLE
The app doesn't connect to the external signaling server after the server has been restarted

### ISSUE THREAD

**Issue by e-caste** [nextcloud/spreed-ios#1317] opened 2023-07-30 07:07 UTC
## Steps to reproduce
1. Update then bring up the Nextcloud server (in my case, with `docker compose up -d`)
2. Use Talk iOS: it very quickly connects to the signaling server in every chat
3. Back up the server (in my case, with `docker compose down`, then back up, then `docker compose up -d`)

### Expected behaviour
Talk iOS can connect to the signaling server without issue.

### Actual behaviour
Talk iOS can't connect to the signaling server anymore, which I notice from the disabled call buttons:
![image](https://github.com/nextcloud/talk-ios/assets/48513706/03755444-ee50-49b2-b871-322fd8be655c)
The effects of this are:
- I can't perform any calls in any chat
- I can't see the typing indicator
- the app takes 10-15 seconds to send a message (which is unfeasibly long when you're outside - the sending of the message can be triggered more quickly by tapping back at the top left and then re-joining the chat, which is horrible UX)

## Device information

**Device:** iPhone X

**iOS version:** 16.5.1 (c)

**Talk version:** 17.0.0

## Server information

**Nextcloud version:** (see admin overview page: `/index.php/settings/admin/overview`) 27.0.1

**Talk version:** (see apps admin page: `/index.php/settings/apps`) 17.0.3

**Custom Signaling server configured:** yes/no and version (see talk admin settings: `/index.php/settings/admin/talk#signaling_server`) yes, app says version Unknown (when it could connect it showed a commit number), I have configured strukturag/nextcloud-spreed-signaling:1.1.3 which is the latest one

**Custom TURN server configured:** yes/no (see talk admin settings: `/index.php/settings/admin/talk#turn_server`) yes

**Custom STUN server configured:** yes/no (see talk admin settings: `/index.php/settings/admin/talk#stun_server`) yes

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

**Comment by SystemKeeper** [comment] 2023-07-30 12:57
Hey e-caste,

just to state the obvious, do backups only outside of working hours 😉 
Jokes aside... Some things to note:

* Sending a message does not rely on the external signaling server, so when sending a message takes 10-15s after a restart, I would assume it's because the NC instance is not responding fast enough. Maybe you could verify the requests on the server in that case? You could also verify on web and take a look at the requests. That could also be an issue for the signaling server, because it needs to request capabilities from the NC instance.
* When we loose the connection to the external signaling server, we try to reconnect almost immediately. If that fails, we have an increasing wait time to not DOS the server (see https://github.com/nextcloud/talk-ios/blob/a1545167b9b9233efef3a88a98e225e9052c3a6f/NextcloudTalk/NCExternalSignalingController.m#L208-L222) up to 16s. But that also might depends on other factors, so if the attempt before that needs to time out, it can be higher than 16s.

To get some details on what's happening, you can take a look at the logfiles. Go to the native iOS files app -> Nextcloud Talk -> logs. There you can find informations about what the external signaling connection and attempts.

**Comment by SystemKeeper** [comment] 2023-08-05 12:50
> * the app takes 10-15 seconds to send a message (which is unfeasibly long when you're outside - the sending of the message can be triggered more quickly by tapping back at the top left and then re-joining the chat, which is horrible UX)

 Hey, is it possible for you to reproduce this „state“ every time? If so, could you please check if scrolling has the same effect as leaving and joining ? So the cell gets reloaded when scrolling out of sight and then back again?

**Comment by SystemKeeper** [comment] 2023-08-05 12:51
Alternatively check if the message arrives on the other side, but we still show the spinner?

**Comment by e-caste** [comment] 2023-08-22 17:39
@SystemKeeper sorry for not replying earlier. I'll try and check the logs, but in the meantime I have come up with the idea that this behavior may be related to the phone being in Low Power Mode. Being summer, I need to preserve my battery as much as possible, thus I have my phone almost always in Low Power Mode; with this setting enabled, I see this issue much more frequently. Do you think a correlation could be possible?

**Comment by SystemKeeper** [comment] 2023-08-23 06:14
There’s only one place in talk ios where we check for low battery mode and that is fetching updates in the background. In case it’s enabled, we don’t try to retrieve the latest chat messages. But that has no impact on the issue you’re seeing. No idea if iOS is doing something weird on its own, but I tend to say that this is not related.

**Comment by SystemKeeper** [comment] 2023-08-25 18:18
@e-caste we improved logging for the external signaling server and fixed a possible race condition in 17.1 Beta 3. Can you try to reproduce the issue with this version?

**Comment by e-caste** [comment] 2023-08-28 10:20
Hi @SystemKeeper that's great to hear. Unfortunately I don't have a device to test the beta app on at the moment, I'll tell you when the update gets published to the App Store

**Comment by SystemKeeper** [comment] 2023-08-28 15:28
I think I found something that we are not handling correctly: https://github.com/strukturag/nextcloud-spreed-signaling/issues/543 
There's some room for improvement for session resuming on our end at least.

**Comment by e-caste** [comment] 2023-09-02 14:38
Okay, I've finally had some time to investigate the issue. It was simpler than expected: just before the issue came up, I updated the Docker strukturag/nextcloud-spreed-signaling from version 1.1.2 to 1.1.3. I believe there is a breaking change that is not listed in the [release notes of v1.1.3](https://github.com/strukturag/nextcloud-spreed-signaling/releases/tag/v1.1.3). This is my nginx configuration for v1.1.2:
```
location /standalone-signaling/ {
    proxy_pass http://SPREED_SIGNALING_CONTAINER_NAME/;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}

location /standalone-signaling/spreed {
    proxy_pass http://SPREED_SIGNALING_CONTAINER_NAME/spreed;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}
```
The only logs that I found useful were those of Nextcloud Talk in the browser console. The errors, if I use the above nginx config with v1.1.3, are:
```
[Debug] Connecting to wss://SIGNALING_ADDRESS/standalone-signaling/spreed for CHAT_ID (talk-main.js, line 2)
[Debug] Connected (talk-main.js, line 2)
[Debug] Connected – Event {isTrusted: true, type: "open", target: WebSocket, …} (talk-main.js, line 2)
Event {isTrusted: true, type: "open", target: WebSocket, currentTarget: WebSocket, eventPhase: 2, …}Eventbubbles: falsecancelBubble: falsecancelable: falsecomposed: falsecurrentTarget: nulldefaultPrevented: falseeventPhase: 0isTrusted: truereturnValue: truesrcElement: WebSocket {url: "wss://SIGNALING_ADDRESS/standalone-signaling/spreed", readyState: 3, bufferedAmount: 0, onopen: null, onmessage: null, …}WebSockettarget: WebSocket {url: "wss://SIGNALING_ADDRESS/standalone-signaling/spreed", readyState: 3, bufferedAmount: 0, onopen: null, onmessage: null, …}WebSockettimeStamp: 78514type: "open"Event Prototype
[Debug] Welcome received – {type: "welcome", welcome: Object} (talk-main.js, line 2)
{type: "welcome", welcome: Object}Objecttype: "welcome"welcome: {version: "12de5a9b71afef06eaf171099712ef0a5f6ca0c4", features: Array}ObjectObject Prototype
[Debug] Hello response received – {id: "1", type: "error", error: {code: "token_expired", message: "The token is expired."}} (talk-main.js, line 2)
[Error] Could not connect to server – {id: "1", type: "error", error: {code: "token_expired", message: "The token is expired."}}
	(anonymous function) (talk-main.js:2:5240290)
	(anonymous function)
	(anonymous function) (talk-main.js:2:5235690)
	(anonymous function)
```
Same logs with v1.1.2 (after this, Talk and Talk iOS _immediately_ join and leave the chat as intended):
```
[Debug] Connecting to wss://SIGNALING_ADDRESS/standalone-signaling/spreed for CHAT_ID (talk-main.js, line 2)
[Debug] Connected – Event {isTrusted: true, type: "open", target: WebSocket, …} (talk-main.js, line 2)
Event {isTrusted: true, type: "open", target: WebSocket, currentTarget: WebSocket, eventPhase: 2, …}Event
[Debug] Welcome received – {type: "welcome", welcome: Object} (talk-main.js, line 2)
{type: "welcome", welcome: Object}Object
[Debug] Hello response received – {id: "1", type: "hello", hello: Object} (talk-main.js, line 2)
{id: "1", type: "hello", hello: Object}Object
[Debug] Joined (talk-main.js, line 2)
[Debug] Join room – "CHAT_ID" (talk-main.js, line 2)
[Debug] Joined (2) (talk-main.js, line 2)
{id: "2", type: "room", room: Object}
"CHAT_ID"
```
The temporary fix for me is to revert to v1.1.2, but I would like to understand what's causing the issue and how can I make my config work with new versions.

**Comment by SystemKeeper** [comment] 2023-09-05 12:24
Thanks for the additional infos. So you also have trouble with web when using 1.1.3? Just from the changelog between 1.1.2 and 1.1.3 I can’t spot a breaking change… 
Is the signaling server running on the same server as the nextcloud instance? If not, can you check the time difference between the two?

**Comment by SystemKeeper** [comment] 2023-09-05 13:36
Also CC @fancycode. Not sure if there’s a breaking change between 1.1.2 and 1.1.3 I am unable to see? It doesn’t sound like it’s related to the issue of duplicated joins 🧐

**Comment by fancycode** [comment] 2023-09-05 13:41
The error `{code: "token_expired", message: "The token is expired."}` hints that the connection token created by Nextcloud is expired / not valid yet when connecting to the signaling server. As @SystemKeeper suggested, you should check the time on the machines running Nextcloud and the signaling server.

I don't see a breaking change between 1.1.2 and 1.1.3 either. Does the problem happen all the time and for all clients?

**Comment by SystemKeeper** [comment] 2023-09-30 09:22
@e-caste any feedback on the questions above ?

**Comment by e-caste** [comment] 2023-10-12 21:23
Hey @SystemKeeper sorry for the delay.  
The deployment is a docker-compose on the same server so the time should be the same as far as I know.  
This bug could also be caused by the fact that I wasn't restarting the nginx-proxy deployment after restarting the one of Nextcloud, which meant not all containers were set up correctly after the backup. I'll try again with v1.1.3 of the signaling server and this change in my backup script and let you know.

(By the way, if you use nginx-proxy and Nextcloud, I'm curious if a docker-compose restart of both can be avoided in this case)

**Comment by SystemKeeper** [comment] 2024-02-15 20:59
I'll close this issue for now as it seems unrelated to talk-ios.

**Closed as not planned by SystemKeeper** 2024-02-15 20:59 UTC
Labels: bug, 0. Needs triage
