### ISSUE TITLE
Better way to handle Pictures/Videos

### ISSUE THREAD

**Issue by warnerbryce** [nextcloud/spreed-ios#1354] opened 2023-09-04 10:05 UTC
**Is your feature request related to a problem? Please describe.**
It's an improvement.

**Describe the solution you'd like**
Like in Messenger / Whatsapp / Signal when you have several pictures / videos in the chat, you click on one of them for having a closer view and you can swipe left or right to see oldest / newest media but you can't swipe left or right in Nextcloud Talk.
You have to close the media, then click the next one. It's quite annoying. 

This way of handling medias make an argument against Nextcloud Talk in the functionality sheet between other secured chat app.

This problem applies to the Android App too.

**Comment by warnerbryce** [comment] 2024-04-28 15:13
A little UP please. 
I spoke about that during last year Nextcloud Hub Release Keynote, they said in the chat : Good Idea, we will add this in the roadmap... 
But they forgot... 
Don't forget about this, it's really a deal breaker for using Nextcloud Talk on Android and iOS.

**Comment by SystemKeeper** [comment] 2024-04-29 17:19
Hey, thanks for your interest in this feature! 

> But they forgot...

Putting something on a roadmap does not imply that development of that feature starts immediately - in the worst case it could also be removed again from the roadmap. There are multiple ways to show interest in a feature:

* Create a pull request with that feature
* Upvote the corresponding issue (upvoting of the first comment is enough, no need for "me too" posts)
* Talk to Nextcloud GmbH in case you're a customer

> Don't forget about this, it's really a deal breaker for using Nextcloud Talk on Android and iOS.

While I understand that it's not the best way of handling images right now, I wouldn't consider it a deal breaker, tbh.

If this is an issue for Talk on Android as well, please open an issue on the corresponding issue tracker, as we can only track Talk iOS here.

**Comment by SystemKeeper** [comment] 2024-05-02 04:57
Duplicate of https://github.com/nextcloud/talk-ios/issues/699

**Closed as not planned by SystemKeeper** 2024-05-02 04:57 UTC
Labels: enhancement, 0. Needs triage
