### ISSUE TITLE
Unable to establish audio or video calls with Nextcloud iOS client with local HPB signaling server

### ISSUE THREAD

**Issue by slantedbit** [nextcloud/spreed-ios#1082] opened 2023-02-16 12:36 UTC
## Steps to reproduce
1. Start Nextcloud Talk iOS App 15.2.5 on iPhone X with iOS 16.3
2. Create a group call or try to answer an incoming call
3. Call buttons grayed out / disabled. Unable to answer incoming calls.

### Expected behaviour
Nextcloud Talk App should be able to establish audio or video call connections just like it works from browser on same device.

### Actual behaviour
Audio and video calls are unavailable from Nextcloud Talk iOS app, but creation of groups and chat is working. However, audio and video calls are working when using e.g. Safari / browser on same Apple mobile device. The Nextcloud Talk is also working on Android clients and desktop PC.

The Nextcloud Talk iOS app is able to make audio/video calls if the custom HPB signaling server is disabled. However, as said, the signaling server is working with any other client than iOS.

Problem is identical in local network and from a public IP / internet connection outside firewall.
Server is using valid Let's Encrypt -assigned SSL certificate.

## Device information

**Device:** iPhone X

**iOS version:** 16.3

**Talk version:** 15.2.5

## Server information

**Nextcloud version:** 25.0.3

**Talk version:** 15.0.3

**Custom Signaling server configured:** yes (v. 1.00 on Ubuntu)
**Custom TURN server configured:** yes (Coturn-4.5.2)
**Custom STUN server configured:** yes

### Server log (data/nextcloud.log)
No error messages in server logs or service statuses related to the problem. Seems not a problem at server side.

![diagnostics_](https://user-images.githubusercontent.com/125564994/219362408-d9d9326d-1b86-47f0-9873-61eb34a51234.jpg)
![diagnostics](https://user-images.githubusercontent.com/125564994/219361100-9b1ab155-f559-4ac1-89b1-b4d744942a14.jpg)
![call_buttons_grayed_out](https://user-images.githubusercontent.com/125564994/219361091-3aa7c51a-18df-4f48-a199-9f7ef28f460c.jpg)

**Comment by SystemKeeper** [comment] 2023-02-16 12:39
Hey, thanks for your report! I see that the `Version` field in the diagnostic panel is `Unknown`. So it looks like the app is unable to establish a connection with your HPB. Is your signaling server using the same certificate than the instance or is there a difference?

**Comment by slantedbit** [comment] 2023-02-16 13:34
> Hey, thanks for your report! I see that the `Version` field in the diagnostic panel is `Unknown`. So it looks like the app is unable to establish a connection with your HPB. Is your signaling server using the same certificate than the instance or is there a difference?

Yes, this "Unknown" seems like the only lead to the problem. The signaling server is on same server with the Nextcloud. Maybe not a textbook solution, but works otherwise without problems. Both are behind same Apache reverse proxy with same certificate.

**Comment by SystemKeeper** [comment] 2023-02-16 15:02
> Yes, this "Unknown" seems like the only lead to the problem.

Pretty sure, yes. Without a connection with the HPB we can't setup a call, so that's why the buttons stay disabled in this case.

> The signaling server is on same server with the Nextcloud. Maybe not a textbook solution, but works otherwise without problems

I don't see a problem there in general. If the connection is possible, the certificate is valid (and is ATS compliant) I don't see why it shouldn't work.

You say that you have both behind the same reverse proxy, the reverse proxy is also the one which is added as a signaling server in talk, right?

Two things you can try:
* Take a look at the debug logs of talk-ios. You find them when you open the Files app (the native one, not the nextcloud one) and look in the debug.log from today. If I'm not mistaken, the error should be logged if the HPB connection fails.
* Other than that, the obvious thing would be to remove the account and set it up again... 😕

**Comment by slantedbit** [comment] 2023-02-16 16:10
>     * Take a look at the debug logs of talk-ios. You find them when you open the Files app (the native one, not the nextcloud one) and look in the debug.log from today. If I'm not mistaken, the error should be logged if the HPB connection fails.

Attached log when trying to answer an incoming call using the client. Some error indications highlighted.
 
![debug_log](https://user-images.githubusercontent.com/125564994/219421175-5a7a3014-efa4-4aaa-a478-dabd09593e4e.png)

**Comment by slantedbit** [comment] 2023-02-16 16:32
Tested the same websocket using https://www.piesocket.com/websocket-tester

- Connection log will appear here
- Connecting to: wss://cloud.***********.com:/standalone-signaling/spreed
- Connection Established
▼ {"type":"welcome","welcome":{"version":"d56e67387b485f252812d23001b435eb559d8e5a","features":["audio-video-permissions","hello-v2","incall-all","mcu","simulcast","switchto","transient-data","update-sdp","virtual-sessions","welcome"]}}
▼ {"type":"bye","bye":{"reason":"hello_timeout"}}
- Connection closed

![wss](https://user-images.githubusercontent.com/125564994/219428535-57cb2d90-9f58-4f21-bc7e-1fe2765040ce.jpg)

**Comment by SystemKeeper** [comment] 2023-02-16 16:43
Thanks for the additional information! The problem is not the disconnected websocket or nil websocket, the main problem is the reconnect directly after a connect attempt. It most probably means, that the websocket failed and tries to reconnect. Sadly we only log that error to the console, not to the log file, so hard to guess what fails.

Is there a chance you can let me know which HPB url you use? You can find my mail in the header of this file
https://github.com/nextcloud/talk-ios/blob/master/NextcloudTalk/CallsFromOldAccountViewController.swift

**Comment by SystemKeeper** [comment] 2023-02-17 06:54
> * wss://cloud.***********.com:/standalone-signaling/spreed

I think we can close this issue. After testing we found a additional „:“ at the end of the signaling server url (see above). Looks like Browsers ignore this, but the iOS native APIs fail. After correcting the URL in the admin settings of talk, the connection worked as expected.

**Closed as completed by SystemKeeper** 2023-02-17 06:54 UTC
Labels: bug, 0. Needs triage
