### ISSUE TITLE
The app scrolls the chat up and down to random dates in a crazy way after restoring the Nextcloud server installation

### ISSUE THREAD

**Issue by e-caste** [nextcloud/spreed-ios#943] opened 2022-10-21 10:35 UTC
## Steps to reproduce
1. have a working Nextcloud 24
2. try to update to 25 and break everything (see https://github.com/nextcloud/server/issues/34679 for my journey)
3. finally get back a working 24 version of 2 days before
4. open Talk iOS
5. short chats (100s of messages) open correctly
6. long chats (1000s or tens of 1000s of messages) when opened scroll/jump up and down between random dates every half second and prevent the user to send any text message, also overheating the phone

Same behavior on the web version of Nextcloud Talk, so the bug could be at a higher level.

Fix: wait for ~10 minutes, after you've sent a message it stops randomly jumping between dates.

### Expected behaviour
Not this crazy stuff.

### Actual behaviour
This crazy stuff.

## Device information

**Device:** iPhone X and iPhone 12

**iOS version:** 16.0.3

**Talk version:** 15.0.0

## Server information

**Nextcloud version:** 24.0.6

**Talk version:** 14.0.5

**Custom Signaling server configured:** no

**Custom TURN server configured:** yes

**Custom STUN server configured:** yes

### Server log (data/nextcloud.log)
<details>
can't find it on my install, but the Docker app logs are just a lot of `GET`, `PUT`, `DELETE`, and `POST /ocs/v2.php 200`
</details>

**Comment by SystemKeeper** [comment] 2022-10-21 10:38
Hey @e-caste 
my first thought is that the rollback made server and client out of sync and that large blocks of messages are received as new. Can you please try to remove the account having troubles from talk-ios and then add it again?

**Comment by e-caste** [comment] 2022-10-21 10:40
@SystemKeeper forgot to mention that removing the account and logging back in or not doing so is the same, even after logging back in there are a few minutes of jumping up and down.

**Comment by SystemKeeper** [comment] 2022-10-21 10:41
I see, so that might be a issue not related to talk-ios per se. How did you move back to 24 after the upgrade to 25?

**Comment by e-caste** [comment] 2022-10-21 10:43
@SystemKeeper I restored a VM backup. So essentially, point blank. The upgrade to 25 never finished though. The issue is that I had a few messages from the day before the failed upgrade that were already synced to the phone but that are not present in the backup.

**Comment by SystemKeeper** [comment] 2022-10-21 10:45
That's really weird, if you remove the account, there should be no traces left in talk-ios. I mean, you could try re-installing talk-ios and see if that works. Other than that I don't have a good idea right now and not sure this is in the scope of talk-ios unfortunately.

**Comment by e-caste** [comment] 2022-10-21 10:49
@SystemKeeper yes, as I've briefly mentioned in the issue the web version of Nextcloud Talk presents the same behavior. I guess the underlying issue is the way the chat messages get cached to the device. It looks like at the moment all messages need to be cached, so the more you have the longer the time you have to wait for the weird loading behavior. It could potentially be fixed by only caching the most recent messages and then getting the older ones on request when the user scrolls up.

**Comment by SystemKeeper** [comment] 2022-10-21 10:51
Missed the part about web, sorry. If a account is removed, all stored messages are cleared and only the most recent ones should be synced... maybe you can check what requests are made at the server and see if we can figure something out there. But yea, not quite sure.

**Comment by Ivansss** [comment] 2022-10-21 10:57
I guess the problem might be here in the read marker. Maybe it was lost when the server was restored.
Does this conversation show a big number of unread messages @e-caste?
In that case, both the iOS app and the web will start fetching messages from the beginning in blocks.
That would be the reasons of the jumps.
The web and the iOS app will fetch the whole chat history so the jumps will stop when this is done.
As a workaround you could mark that conversations as read so only the last block with be fetched and cached.

**Comment by e-caste** [comment] 2022-10-21 10:58
@SystemKeeper A lot of `GET /ocs/v2.php/apps/spreed/api/v1/chat/<chatid>?includeLastKnown=0&lastCommonReadId=<censored>&lastKnownMessageId=<censored>&limit=100&lookIntoFuture=1&setReadMarker=1&timeout=30 HTTP/1`. Looks like the app is trying to get way more than just the last 100 messages, since each request is for a block of 100. If I knew where to look I'd look for the API calls that are done at chat restore.

**Comment by e-caste** [comment] 2022-10-21 11:01
@Ivansss I had just 1 unread message. But I'm quite sure the app is re-downloading the whole chat history as you've mentioned. There may be a bug that triggers the full re-caching when the app loses the sync with the server (in this case, the app had more recent messages than the last ones on the server). A fix could be to detect the desync state, if detected scrap the whole chat and re-cache only the most recent messages.

**Comment by SystemKeeper** [comment] 2022-10-21 12:53
Might be interesting to see if the `lastKnownMessageId` changes over time. You can take a look at how the API works at https://nextcloud-talk.readthedocs.io/en/latest/chat/ and the implementation should be at https://github.com/nextcloud/spreed/tree/stable24/lib/Chat for 24.
Also you might want to check if the DB is actually updated with the messageIds and read marker.

**Comment by SystemKeeper** [comment] 2022-11-03 12:21
Hey @e-caste I will close this issue for now. If there's a way to reproduce this issue without downgrading, please let us know.

**Closed as not planned by SystemKeeper** 2022-11-03 12:21 UTC
Labels: bug, 0. Needs triage
