### ISSUE TITLE
Unable to start an audio or video call after changing the network on iphone

### ISSUE THREAD

**Issue by Yo-DDV** [nextcloud/spreed-ios#964] opened 2022-10-29 15:21 UTC
## Steps to reproduce
1. Initiate a call from A to B, the call is established and working
2. Hang up the call from A to B, switch from wifi to 4G or from 4G to wifi
3. Relaunch the call from A to B, the connection can no longer be established (waiting for the connection to be established)

### Expected behaviour
The call should work again, even after changing the network / public ip

### Actual behaviour
The connection cannot be established until I close the application then restart it, then restart the call

## Device information

**Device:** iPhone X/iPad Y/…
Iphone 13 pro max

**iOS version:** 10/…
16.0
**Talk version:** 11.1.1
15.0.0
## Server information

**Nextcloud version:** (see admin overview page: `/index.php/settings/admin/overview`)
24.0.5
**Talk version:** (see apps admin page: `/index.php/settings/apps`)
14.0.5
**Custom Signaling server configured:** yes/no and version (see talk admin settings: `/index.php/settings/admin/talk#signaling_server`)
yes
**Custom TURN server configured:** yes/no (see talk admin settings: `/index.php/settings/admin/talk#turn_server`)
yes
**Custom STUN server configured:** yes/no (see talk admin settings: `/index.php/settings/admin/talk#stun_server`)
yes
### Server log (data/nextcloud.log)

```
Insert your server log here
```

**Comment by SystemKeeper** [comment] 2022-10-29 16:11
Hey @TBI-NS,
thanks for opening the issue. Just to make sure, what happens if you change conversations between step 2 and 3? So
* Call from A -> B
* Leave call
* Switch from Wifi to 4G
* Leave conversation / join another conversation
* Call from A -> B again

Also, does it matter which of the two is the one who's switching the networks?

**Comment by TBI-NS** [comment] 2022-10-29 17:03
> Hey @TBI-NS, thanks for opening the issue. Just to make sure, what happens if you change conversations between step 2 and 3? So
> 
> * Call from A -> B
> * Leave call
> * Switch from Wifi to 4G
> * Leave conversation / join another conversation
> * Call from A -> B again
> 
> Also, does it matter which of the two is the one who's switching the networks?

Hello, thank you for your quick response!

So following the procedure you just gave me, the calls work after changing the wifi network to 4G.

Obviously changing the conversation and starting another call, then hanging up and returning to the call that could not be answered solved the problem.

regarding your last question, the problem is valid on both sides, A to B and B to A when one of the two changes from wifi to 4G

 Thanks !

**Comment by SystemKeeper** [comment] 2022-11-10 15:10
Hey @TBI-NS thank you for providing additional information/tests. We were able to reproduce this. I expect #975 to fix this issue once it's merged and released!

**Comment by TBI-NS** [comment] 2023-01-07 19:13
The problem is solved in 15.2.3! You can close this request. Thanks

**Closed as completed** 2023-01-07 20:03 UTC
Labels: bug, 0. Needs triage
