### ISSUE TITLE
No text notifications on iOS device

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/spreed-ios#851] opened 2022-08-04 19:06 UTC
## Steps to reproduce
1. users send me a messages
2. sudo -u www-data php /var/www/nextcloud/occ notification:test-push --talk username
3.

### Expected behaviour
I should be getting text notification on my ios devices, but it dose work on my windows desktop client and androind client.
Already rebooted the phone, removed and reinstalled the app sent a sudo -u www-data php /var/www/nextcloud/occ notification:test-push --talk admin no luck

I did do a curl https://push-notifications.nextcloud.com and came back with  404 page not found: based on the doc that a good message. 

### Actual behaviour
Not getting notifications on the IOS devices

## Device information

**Device:** iPhone X/iPad Y/…
iPhone 12 Pro
**iOS version:** 10/…
15.6
**Talk version:** 11.1.1
14.0.2
## Server information

**Nextcloud version:** (see admin overview page: `/index.php/settings/admin/overview`)
24.0.3
**Talk version:** (see apps admin page: `/index.php/settings/apps`)
14.0.3
**Custom Signaling server configured:** yes/no and version (see talk admin settings: `/index.php/settings/admin/talk#signaling_server`)

**Custom TURN server configured:** yes/no (see talk admin settings: `/index.php/settings/admin/talk#turn_server`)
yes
**Custom STUN server configured:** yes/no (see talk admin settings: `/index.php/settings/admin/talk#stun_server`)
yes
### Server log (data/nextcloud.log)
<details>

```
None
```
</details>

**Comment by SystemKeeper** [comment] 2022-08-04 19:08
Hey @andyxheli 
Can you post the complete output of the occ command please?
As Android works, I assume no open sessions?
Can you try logout and login again please ?

**Comment by AndyXheli** [comment] 2022-08-04 19:12
Hey @SystemKeeper Here what i get from the OCC with the android talk logged in 


Trying to push to 5 devices

Language is set to en
Private user key size: 1704
Public user key size: 451
Identified 1 Talk devices and 4 others.

Device token:1206
Device public key size: 451
Data to encrypt is: {"nid":2619,"app":"admin_notification_talk","subject":"Testing push notifications","type":"admin_notifications","id":"62ec1949"}
Signed encrypted push subject
Push notification sent successfully

**Comment by AndyXheli** [comment] 2022-08-04 19:13
Here a log with Android Talk Logged out. Also as soon as i did a logout on the Android Talk and did a occ push it worked but the android app was closed before 

Trying to push to 2 devices

Language is set to en
Private user key size: 1704
Public user key size: 451
Identified 0 Talk devices and 2 others.

Device token:1222
Device public key size: 451
Data to encrypt is: {"nid":2623,"app":"admin_notification_talk","subject":"Testing push notifications","type":"admin_notifications","id":"62ec1a17"}
Signed encrypted push subject

Device token:1428
Device public key size: 451
Data to encrypt is: {"nid":2623,"app":"admin_notification_talk","subject":"Testing push notifications","type":"admin_notifications","id":"62ec1a17"}
Signed encrypted push subject
Push notification sent successfully

**Comment by AndyXheli** [comment] 2022-08-04 19:15
Just logged back into the android talk app and no more ios notifications.

Heres the occ output

Trying to push to 3 devices

Language is set to en
Private user key size: 1704
Public user key size: 451
Identified 1 Talk devices and 2 others.

Device token:1447
Device public key size: 451
Data to encrypt is: {"nid":2625,"app":"admin_notification_talk","subject":"Testing push notifications","type":"admin_notifications","id":"62ec1a94"}
Signed encrypted push subject

**Comment by SystemKeeper** [comment] 2022-08-04 19:16
So there's only one iOS device registered at your server (which probably is the android device...). So the iOS talk client is not there anymore. There were some reports about this and all were fixed by logging out and login again. Can you try that please?
(Not saying there's no problem, just want to make sure this works as a workaround)

**Comment by AndyXheli** [comment] 2022-08-04 19:19
So i did a logout and login on the Android Talk and same issue. If I keep the android talk logged out then notifications work. 
I also did a logout and back in on the IOS device while android talk was logged in and same results no notifications. Did you want me to try something else?

Yes, i only have one ios device iphone

**Comment by SystemKeeper** [comment] 2022-08-04 19:21
> Identified 0 Talk devices and 2 others.

Just wondering, the notifications you received, after the android device was logged out, did you receive those in talk-ios or the files-ios app?
(because when there're no talk devices found, the notification will be sent to non-talk devices, see https://github.com/nextcloud/notifications/blob/4317a0959aa4ba26787876b727c8e8eb0b4e1899/lib/Push.php#L197-L200)

**Comment by AndyXheli** [comment] 2022-08-04 19:25
So i remove both nextcloud files on android & ios and remove talk on android i logged into talk via ios and pushed a notification via occ heres what i got. I did get the alert on my windows desktop client. I must of been getting alerts on the ios via nextcloud files and not talk

Trying to push to 1 devices

Language is set to en
Private user key size: 1704
Public user key size: 451
Identified 0 Talk devices and 1 others.

Device token:1428
Device public key size: 451
Data to encrypt is: {"nid":2634,"app":"admin_notification_talk","subject":"Testing push notifications","type":"admin_notifications","id":"62ec1dd1"}
Signed encrypted push subject


![image](https://user-images.githubusercontent.com/59488153/182937001-06837691-862e-457e-a9ea-93f8cd482de1.png)

**Comment by AndyXheli** [comment] 2022-08-04 19:33
I also did a logout from my widnows desktop client the only client thats logged in right now is the IOS talk app and here the occ output 

root@nextcloud:~# sudo -u www-data php /var/www/nextcloud/occ notification:test-push --talk admin
No devices found for user


Im doing another logout and login from ios talk and see what happens

**Comment by SystemKeeper** [comment] 2022-08-04 19:34
> No devices found for user

~Ok, after all devices are removed and you logout/login in the talk ios app, what happens then?~ too slow..

**Comment by AndyXheli** [comment] 2022-08-04 19:36
Here's what i get

root@nextcloud:~# sudo -u www-data php /var/www/nextcloud/occ notification:test-push --talk admin
Trying to push to 1 devices

Language is set to en
Private user key size: 1704
Public user key size: 451
Identified 1 Talk devices and 0 others.

Device token:1451
Device token is valid
Device public key size: 451
Data to encrypt is: {"nid":2641,"app":"admin_notification_talk","subject":"Testing push notifications","type":"admin_notifications","id":"62ec1f8b"}
Signed encrypted push subject
Push notification sent, but 1 failed


root@nextcloud:~# sudo -u www-data php /var/www/nextcloud/occ notification:test-push --talk admin
Trying to push to 1 devices

Language is set to en
Private user key size: 1704
Public user key size: 451
Identified 1 Talk devices and 0 others.

Device token:1451
Device public key size: 451
Data to encrypt is: {"nid":2642,"app":"admin_notification_talk","subject":"Testing push notifications","type":"admin_notifications","id":"62ec1f91"}
Signed encrypted push subject
Deleting device because it is unknown by the push server: hos+2t3wblaHHyOI4PhfuJNat9Q4bufe9nBP0m6u6Cx5XF07n7d5jkhNpO3dqhN5LPPHVYyq9zPQr54KkwAGnQ==
Push notification sent, but 1 failed

**Comment by AndyXheli** [comment] 2022-08-04 19:38
I just ran another one after those errors 
Deleting device because it is unknown by the push server: hos+2t3wblaHHyOI4PhfuJNat9Q4bufe9nBP0m6u6Cx5XF07n7d5jkhNpO3dqhN5LPPHVYyq9zPQr54KkwAGnQ==
Push notification sent, but 1 failed

and now i get 

root@nextcloud:~# sudo -u www-data php /var/www/nextcloud/occ notification:test-push --talk admin
No devices found for user

**Comment by AndyXheli** [comment] 2022-08-04 19:41
Can this have something to do with the https://apps.nextcloud.com/apps/notify_push app ?

**Comment by SystemKeeper** [comment] 2022-08-04 19:44
Hm. So there's something wrong with registering the device at the push proxy. When trying to send a notification, an error is return and then the device is removed, because it is unkown.

Do you have access to a mac device and can get the console logs from the talk app by any chance?

One last thing that would be interesting to know, would if you're currently on wifi, could you try cellular (so login to talk while on cellular and then try the occ command)?

**Comment by SystemKeeper** [comment] 2022-08-04 19:45
> Can this have something to do with the https://apps.nextcloud.com/apps/notify_push app ?

No, this has nothing to do with the push notifications we're talking about here.

**Comment by AndyXheli** [comment] 2022-08-04 19:47
> Hm. So there's something wrong with registering the device at the push proxy. When trying to send a notification, an error is return and then the device is removed, because it is unkown.
>  yea very strange

> Do you have access to a mac device and can get the console logs from the talk app by any chance?
> No im sorry i dont have access to a mac. I just sold it :( damn should i kept it 

> One last thing that would be interesting to know, would if you're currently on wifi, could you try cellular (so login to talk while on cellular and then try the occ command)?
Working on that now for you.

**Comment by AndyXheli** [comment] 2022-08-04 19:52
Same results while on Mobile data. I removed the ios app and i installed it via mobile and logged in via mobile push the occ command 

root@nextcloud:~# sudo -u www-data php /var/www/nextcloud/occ notification:test-push --talk admin
Trying to push to 1 devices

Language is set to en
Private user key size: 1704
Public user key size: 451
Identified 1 Talk devices and 0 others.

Device token:1453
Device token is valid
Device public key size: 451
Data to encrypt is: {"nid":2646,"app":"admin_notification_talk","subject":"Testing push notifications","type":"admin_notifications","id":"62ec231c"}
Signed encrypted push subject
Push notification sent, but 1 failed
root@nextcloud:~# sudo -u www-data php /var/www/nextcloud/occ notification:test-push --talk admin
Trying to push to 1 devices

Language is set to en
Private user key size: 1704
Public user key size: 451
Identified 1 Talk devices and 0 others.

Device token:1453
Device public key size: 451
Data to encrypt is: {"nid":2647,"app":"admin_notification_talk","subject":"Testing push notifications","type":"admin_notifications","id":"62ec2323"}
Signed encrypted push subject
Deleting device because it is unknown by the push server: SjZem1F4oOss9vw7fWUH3Vu8m6A2gqtffoKvVgUQ+unKM5zVLC98MW7ca3UfuxFtI8TDRVvXjVAZMLuNf8V/vw==
Push notification sent, but 1 failed

**Comment by SystemKeeper** [comment] 2022-08-04 20:00
> No im sorry i dont have access to a mac. I just sold it :( damn should i kept it

There are ways to get those logs on windows as well. One easy way is this https://imazing.com/guides/how-to-access-iphone-ipad-console-log. I've used it before, worked good for me, but obviously that's nothing offically from apple and falls under "use at your own risk" 😅 Probably there're other ways as well, not sure. 

> Same results while on Mobile data

Thank you for trying! I just removed my account from the app and re-added it and it works fine, so I think the push proxy itself works.


The console logs could (not sure) help, but other than that, I'm out of ideas right now...

**Comment by AndyXheli** [comment] 2022-08-04 20:02
Thank you! im going to give it a try and let you know. Do you want me to remove and reinstall the app and then get the con logs ? 

yea i just asked my wife she has an ipad and iphone and shes getting them on both so i dont get it haha

**Comment by SystemKeeper** [comment] 2022-08-04 20:10
It should be enough when you remove the account from the app and then login again. You can search for "NextcloudTalk" (which is the process name). Usually there should be messages like this
* `Push Notifications Key Pair generated:` _(following the public key)_
* `Subscribed to NC server successfully.`
* `Subscribed to Push Notification server successfully.?`

Any error would be interesting to know

**Comment by AndyXheli** [comment] 2022-08-04 20:45
@SystemKeeper  

I don't see anything with Push Notifications Key Pair generated. hoepfully i didnt upload anything sensitive info in these logs 
	
Line  996: Aug  4 15:32:42 AX-iPhone NextcloudTalk[1270] <Notice>: Subscribed to NC server successfully.
Line 1273: Aug  4 15:32:42 AX-iPhone NextcloudTalk[1270] <Notice>: Subscribed to Push Notification server successfully.

Line 233: Aug  4 15:32:26 AX-iPhone NextcloudTalk(UIKitCore)[1270] <Error>: Unable to simultaneously satisfy constraints.
Line  264: Aug  4 15:32:26 AX-iPhone NextcloudTalk(UIKitCore)[1270] <Error>: Unable to simultaneously satisfy constraints.
Line  293: Aug  4 15:32:26 AX-iPhone NextcloudTalk(UIKitCore)[1270] <Error>: Unable to simultaneously satisfy constraints.
Line  320: Aug  4 15:32:26 AX-iPhone NextcloudTalk(UIKitCore)[1270] <Error>: Unable to simultaneously satisfy constraints.
Line  344: Aug  4 15:32:26 AX-iPhone NextcloudTalk(UIKitCore)[1270] <Error>: Unable to simultaneously satisfy constraints.
Line  368: Aug  4 15:32:26 AX-iPhone NextcloudTalk(UIKitCore)[1270] <Error>: Unable to simultaneously satisfy constraints.
Line  401: Aug  4 15:32:26 AX-iPhone NextcloudTalk(UIKitCore)[1270] <Error>: Unable to simultaneously satisfy constraints.
Line  554: Aug  4 15:32:28 AX-iPhone NextcloudTalk(UIKitCore)[1270] <Error>: Unable to simultaneously satisfy constraints.
Line  855: Aug  4 15:32:34 AX-iPhone NextcloudTalk(UIKitCore)[1270] <Error>: Snapshotting a view (0x10304b600, UIKeyboardImpl) that is not in a visible window requires afterScreenUpdates:YES.

Line  938: Aug  4 15:32:41 AX-iPhone NextcloudTalk(WebKit)[1270] <Error>: 0x10414fa18 - [pageProxyID=8, webPageID=9, PID=1373] WebPageProxy::didFailProvisionalLoadForFrame: frameID=3, domain=<private>, code=102, isMainFrame=1

Line 1175: Aug  4 15:32:42 AX-iPhone NextcloudTalk[1270] <Notice>: Could not update rooms. Error: Error Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: not found (404)" UserInfo={NSLocalizedDescription=Request failed: not found (404), NSUnderlyingError=0x280ba9380 {Error Domain=com.alamofire.error.serialization.response Code=-1016 "Request failed: unacceptable content-type: text/xml" UserInfo={NSLocalizedDescription=Request failed: unacceptable content-type: text/xml, NSErrorFailingURLKey=https://cloud.axserver.com/ocs/v2.php/apps/spreed/api/v1/room?noStatusUpdate=0, com.alamofire.serialization.response.error.data={length = 286, bytes = 0x3c3f786d 6c207665 7273696f 6e3d2231 ... 0a3c2f6f 63733e0a }, com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x2802e6a00> { URL: https://cloud.axserver.com/ocs/v2.php/apps/spreed/api/v1/room?noStatusUpdate=0 } { Status Code: 404, Headers {

Line 1183: Aug  4 15:32:42 AX-iPhone NextcloudTalk[1270] <Notice>: Error while trying to get rooms: Error Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: not found (404)" UserInfo={NSLocalizedDescription=Request failed: not found (404), NSUnderlyingError=0x280ba9380 {Error Domain=com.alamofire.error.serialization.response Code=-1016 "Request failed: unacceptable content-type: text/xml" UserInfo={NSLocalizedDescription=Request failed: unacceptable content-type: text/xml, NSErrorFailingURLKey=https://cloud.axserver.com/ocs/v2.php/apps/spreed/api/v1/room?noStatusUpdate=0, com.alamofire.serialization.response.error.data={length = 286, bytes = 0x3c3f786d 6c207665 7273696f 6e3d2231 ... 0a3c2f6f 63733e0a }, com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x2802e6a00> { URL: https://cloud.axserver.com/ocs/v2.php/apps/spreed/api/v1/room?noStatusUpdate=0 } { Status Code: 404, Headers {

Line 1354: Aug  4 15:32:44 AX-iPhone NextcloudTalk(AudioToolbox)[1270] <Notice>:         AVHapticPlayer.mm:502   -[AVHapticPlayerChannel resetAtTime:error:]: sending reset event: clientID: 0x10004f6 time: 5285.090

Line 1355: Aug  4 15:32:44 AX-iPhone NextcloudTalk(AudioToolbox)[1270] <Notice>:         AVHapticPlayer.mm:443   -[AVHapticPlayerChannel sendEvents:atTime:error:]: sending event array: clientID: 0x10004f6 atTime: 5285.090

Line 1381: Aug  4 15:32:44 AX-iPhone NextcloudTalk(AudioToolbox)[1270] <Notice>:         AVHapticClient.mm:1410  -[AVHapticClient clientCompletedWithError:]: Client-side (async) finish completion callback for client 0x10004f6 called from server

Line 1382: Aug  4 15:32:44 AX-iPhone NextcloudTalk(AudioToolbox)[1270] <Notice>:         AVHapticClient.mm:1415  -[AVHapticClient clientCompletedWithError:]_block_invoke: Async dispatch: preparing to call completionCallback for client 0x10004f6

Line 1383: Aug  4 15:32:44 AX-iPhone NextcloudTalk(AudioToolbox)[1270] <Notice>:         AVHapticClient.mm:1417  -[AVHapticClient clientCompletedWithError:]_block_invoke: Calling completionCallback 0x280b664f0 and then setting to nil
Line 1393: Aug  4 15:32:44 AX-iPhone NextcloudTalk(AudioToolbox)[1270] <Notice>:         AVHapticClient.mm:1410  -[AVHapticClient clientCompletedWithError:]: Client-side (async) finish completion callback for client 0x10004f6 called from server

Line 1394: Aug  4 15:32:44 AX-iPhone NextcloudTalk(AudioToolbox)[1270] <Notice>:         AVHapticClient.mm:1415  -[AVHapticClient clientCompletedWithError:]_block_invoke: Async dispatch: preparing to call completionCallback for client 0x10004f6

Line 1395: Aug  4 15:32:44 AX-iPhone NextcloudTalk(AudioToolbox)[1270] <Notice>:         AVHapticClient.mm:1422  -[AVHapticClient clientCompletedWithError:]_block_invoke: strongSelf.completionCallback is nil

Line 1442: Aug  4 15:32:45 AX-iPhone NextcloudTalk(UIKitCore)[1270] <Error>: Warning once only: UITableView was told to layout its visible cells and other contents without being in the view hierarchy (the table view or one of its superviews has not been added to a window). This may cause bugs by forcing views inside the table view to load and perform layout without accurate information (e.g. table view bounds, trait collection, layout margins, safe area insets, etc), and will also cause unnecessary performance overhead due to extra layout passes. Make a symbolic breakpoint at UITableViewAlertForLayoutOutsideViewHierarchy to catch this in the debugger and see what caused this to occur, so you can avoid this action altogether if possible, or defer it until the table view has been added to a window. Table view: <UITableView: 0x103816400; frame = (0 0; 390 794); gestureRecognizers = <NSArray: 0x280b6dcb0>; layer = <CALayer: 0x280323580>; contentOffset: {0, 0}; contentSize: {390, 0}; adjustedContentInset: {0, 0, 0, 0}; dataSource: <NCChatViewController: 0x103844200>>

Line 1540: Aug  4 15:33:12 AX-iPhone NextcloudTalk(CFNetwork)[1270] <Notice>: Task <3AE9D02D-0240-496C-8D3A-A73CA880F4B0>.<11> finished with error [-999] Error Domain=NSURLErrorDomain Code=-999 UserInfo={NSErrorFailingURLStringKey=<private>, NSErrorFailingURLKey=<private>, _NSURLErrorRelatedURLSessionTaskErrorKey=<private>, _NSURLErrorFailingURLSessionTaskErrorKey=<private>, NSLocalizedDescription=<private>}

Line 1820: Aug  4 15:33:44 AX-iPhone NextcloudTalk(UIKitCore)[1270] <Error>: Snapshotting a view (0x10382bc00, UIKeyboardImpl) that is not in a visible window requires afterScreenUpdates:YES.

**Comment by SystemKeeper** [comment] 2022-08-04 20:57
> I don't see anything with Push Notifications Key Pair generate

Hm. Subscribing to the NC server and then to the push server only happens after a key was successfully generated. At first glance I don't see a way to let the code run the subscription without the keypair. I'll take a look tomorrow with a fresh pair of eyes ;-) Thanks for the work!

**Comment by AndyXheli** [comment] 2022-08-04 21:00
Thank you for looking at it. I'll try to do a log capture one more time and see if I can see that and upload it for! 

Hope you have a great rest of your night! 

Thanks for everything. 

Happy to help ☺️

**Comment by AndyXheli** [comment] 2022-08-05 00:13
@SystemKeeper keeper got better logs sorry i must of missed the  Push Notifications Key Pair generate. hopefully these logs help. 
[Logs.txt](https://github.com/nextcloud/talk-ios/files/9264225/Logs.txt)

**Comment by SystemKeeper** [comment] 2022-08-05 06:18
Thank you 👍 
Can you check that after Line 14052 the key is actually printed? So is there something like 
```
-----BEGIN PUBLIC KEY-----
....
-----END PUBLIC KEY-----
```

And I assume the device is deleted again when issuing the occ command?

**Comment by AndyXheli** [comment] 2022-08-05 12:16
@SystemKeeper you're welcome. Thank you. did you want me to post the public key ? also i only   see on entry with pubic key in the logs i did a reach with Begin Pubic Key

**Comment by SystemKeeper** [comment] 2022-08-05 12:28
> did you want me to post the public key ?

Not at the moment. From what I understand it looks like talk-ios is doing everything correctly here.  Can you tell me what timezone you're on? 


> And I assume the device is deleted again when issuing the occ command?

This still happened, right?

**Comment by AndyXheli** [comment] 2022-08-05 12:51
> > did you want me to post the public key ?
> 
> Not at the moment. From what I understand it looks like talk-ios is doing everything correctly here.  Can you tell me what timezone you're on? 
> 
> 
My time zone is Central Standart time

> > And I assume the device is deleted again when issuing the occ command?
> 
> This still happened, right?

Yup still happening

**Comment by AndyXheli** [comment] 2022-08-05 14:05
So I logged into a different device an ipad and same issue. :( 

root@nextcloud:~# sudo -u www-data php /var/www/nextcloud/occ notification:test-push --talk admin
Trying to push to 4 devices

Language is set to en
Private user key size: 1704
Public user key size: 451
Identified 2 Talk devices and 2 others.

Device token:1455
Device public key size: 451
Data to encrypt is: {"nid":2698,"app":"admin_notification_talk","subject":"Testing push notifications","type":"admin_notifications","id":"62ed2348"}
Signed encrypted push subject

Device token:1473
Device public key size: 451
Data to encrypt is: {"nid":2698,"app":"admin_notification_talk","subject":"Testing push notifications","type":"admin_notifications","id":"62ed2348"}
Signed encrypted push subject
Deleting device because it is unknown by the push server: qeiWi3/IEFmWqFSUYLpvgIOjnt6bVV52HM0NgDPLPyAPZJBgYDtZ0devowj7m6phAGFvaKGzXQ2j/KVuLifxCg==
Push notification sent, but 1 failed

**Comment by SystemKeeper** [comment] 2022-08-06 07:52
So at this point it looks like this is not a problem of talk, talk-ios or nextcloud. Most likely apples APNS returns an error for the device token, which results in this unknown device message. I can only suggest a few basic things here:
* Reboot the device 
* Remove talk-ios and reinstall it
* Look through the console log after starting the app (make sure it was really closed and not in the background) and look for messages related to apns or device token.

Other than that I’m out of ideas, sorry.

**Comment by AndyXheli** [comment] 2022-08-06 15:30
@SystemKeeper Thank you! I gave it a try but i, not seeing anything. I even tryed diffrent devices same issue the 

Signed encrypted push subject
Deleting device because it is unknown by the push server: FcilkMTyQLiE2vI+kZN7B89QPipCKW/d20AmrABoOPxlrKJcfBaAVG9oDMFJppju4mGMc+fZlM0zyvuLIbVN6w==
Push notification sent, but 1 failed

**Comment by AndyXheli** [comment] 2022-08-06 15:36
Also do you think this will help https://help.nextcloud.com/t/nextcloud-talk-push-notifications-not-working/120873/20 but i have no idea how to even try this

**Comment by SystemKeeper** [comment] 2022-08-06 16:10
Not sure, tbh. I need to take a closer look what implications this might have. Basically you would need to issue a sql command to delete those rows, so this is not without a risk.

But despite looking for a solution, did this happen suddenly or did anything change on your side (iOS, device, nextcloud, etc.)?

**Comment by AndyXheli** [comment] 2022-08-06 16:16
Thank you!! 

So I formated my iPhone and I set it up from scratch and then I download all the all etc then I noticed the Issue I've been using the same nextcloud server for 2 years now and I never had the Issue the I got the android phone so I was using that more so didn't really notice it much I keep one phone for work and one for personal iPhone is for work but over all nothing changed on the server side so wired

**Comment by AndyXheli** [comment] 2022-08-06 16:44
So quick update i took my wifes ipad and i logged in under my account and same reslts no notifiaction but when my wife was logged in they worked now i logged myself out and logged my wife back in and now the notifications dont work for her on the ipad i removed and still the same issue for her. she still logged into her iphone and that work and i also tried to log in her account under my iphone and same issue for her. i dont know why when i logg into these devices under my account something happens its really weird. Hope this helps.

**Comment by SystemKeeper** [comment] 2022-08-06 21:32
Okay, let's try to figure out if this is a device issue or an account issue. Can you please try the following:

* Remove all accounts from talk-ios
* Create a new user in nextcloud (something like "pushtest")
* Login with the newly created user to talk-ios
* Issue the occ test command for "pushtest"
* If the notification is then received, we can assume the device and it's capability to push is working fine.

**Comment by AndyXheli** [comment] 2022-08-06 21:50
@SystemKeeper thank you yup I created a new account sent a text via my account to the new account on that ios and it worked now what in the world happen to my account and why dose that happen

**Comment by SystemKeeper** [comment] 2022-08-06 21:54
Okay, so it does look like the problem is unique to your account then. Are you able to query the database?

**Comment by AndyXheli** [comment] 2022-08-06 21:55
Yes what would you like me to do ? I'm conncted to the database :)

**Comment by SystemKeeper** [comment] 2022-08-06 22:07
Let me preface this with that this is nothing official and at your own risk.

While the pushtest account is still logged in in talk-ios and your user is not, let's find out what's in the db for the pushtest user:

```
SELECT id, uid, token, SUBSTRING(deviceidentifier, 1, 8) AS devident, SUBSTRING(devicepublickeyhash, 1, 8) AS devpublic, SUBSTRING(pushtokenhash, 1, 8) AS pushhash FROM oc_notifications_pushhash WHERE apptype = 'talk' AND uid = 'pushtest';
```

Issue the same thing for your user (same condition):
```
SELECT id, uid, token, SUBSTRING(deviceidentifier, 1, 8) AS devident, SUBSTRING(devicepublickeyhash, 1, 8) AS devpublic, SUBSTRING(pushtokenhash, 1, 8) AS pushhash FROM oc_notifications_pushhash WHERE apptype = 'talk' AND uid = 'andyxheli';
```

Logout the pushtest user and login back your user and then issue the select for your user again.

**Comment by AndyXheli** [comment] 2022-08-06 22:22
MariaDB [nextcloud]> SELECT id, uid, token, SUBSTRING(deviceidentifier, 1, 8) AS devident, SUBSTRING(devicepublickeyhash, 1, 8) AS devpublic, SUBSTRING(pushtokenhash, 1, 8) AS pushhash FROM oc_notifications_pushhash WHERE apptype = 'talk' AND uid = 'pushtest';
+----+----------+-------+----------+-----------+----------+
| id | uid      | token | devident | devpublic | pushhash |
+----+----------+-------+----------+-----------+----------+
| 95 | pushtest |  1508 | Fqrzufwk | eafc17a9  | 7b5686a5 |

While logged into ios talk app im still logged into android talk app 

MariaDB [nextcloud]> SELECT id, uid, token, SUBSTRING(deviceidentifier, 1, 8) AS devident, SUBSTRING(devicepublickeyhash, 1, 8) AS devpublic, SUBSTRING(pushtokenhash, 1, 8) AS pushhash FROM oc_notifications_pushhash WHERE apptype = 'talk' AND uid = 'axheil';
Empty set (0.000 sec)

Also i logged bacm into the iphone that pushtest was working on and now no more notofitions after i logged myself on :( so i logged myself and then i logged pushtest back on and now no more notifications.

**Comment by SystemKeeper** [comment] 2022-08-06 22:23
> uid = 'axheil';

Typo?

**Comment by AndyXheli** [comment] 2022-08-06 22:24
axheli is my username in the cloud or i should be using andyxheli?

**Comment by SystemKeeper** [comment] 2022-08-06 22:25
No, you wrote "axheil" instead of "axheli". It should be the username in your nextcloud instance.

**Comment by AndyXheli** [comment] 2022-08-06 22:27
ops sorry hahha here you go output 


MariaDB [nextcloud]> SELECT id, uid, token, SUBSTRING(deviceidentifier, 1, 8) AS devident, SUBSTRING(devicepublickeyhash, 1, 8) AS devpublic, SUBSTRING(pushtokenhash, 1, 8) AS pushhash FROM oc_notifications_pushhash WHERE apptype = 'talk' AND uid = 'axheli';
+----+--------+-------+----------+-----------+----------+
| id | uid    | token | devident | devpublic | pushhash |
+----+--------+-------+----------+-----------+----------+
| 89 | axheli |  1493 | WD6rkOCJ | 58b22b5f  | b15630aa |
| 98 | axheli |  1514 | 3SIfktgS | 9347a64d  | 7b5686a5 |
+----+--------+-------+----------+-----------+----------+


89 is android 98 is the ios i think i did a query before ios login and 89 was there

**Comment by SystemKeeper** [comment] 2022-08-06 22:49
I think that is as far as we can get here on github. I send you a message in the community, we should continue there, but I don't think there's much we can do.

**Closed as completed** 2022-08-06 22:51 UTC
Labels: bug, 0. Needs triage
