### ISSUE TITLE
Accepting an incoming video call from the lock screen makes the video call buttons invisible

### ISSUE THREAD

**Issue by e-caste** [nextcloud/spreed-ios#1035] opened 2023-01-12 23:23 UTC
## Steps to reproduce
1. Get video called
2. Answer from the lock screen with the phone locked
3. Tap on the "Nextcloud Talk" button in the phone call-like view
4. The other party's video is visible, but no controls are usable (buttons invisible, button to switch call<->chat is off screen but barely visible)

### Expected behaviour
The video call controls (audio output, switch on video, hang up, etc) should be visible like when taking the call from inside the app.

### Actual behaviour
See above, but essentially the only way to fix the behaviour is to kill the app from the app switcher and take the call from within the app.

## Device information

**Device:** iPhone X

**iOS version:** 16.2

**Talk version:** 15.2.3

## Server information

**Nextcloud version:** (see admin overview page: `/index.php/settings/admin/overview`) 25.0.2

**Talk version:** (see apps admin page: `/index.php/settings/apps`) 15.0.2

**Custom Signaling server configured:** yes/no and version (see talk admin settings: `/index.php/settings/admin/talk#signaling_server`) no

**Custom TURN server configured:** yes/no (see talk admin settings: `/index.php/settings/admin/talk#turn_server`) yes

**Custom STUN server configured:** yes/no (see talk admin settings: `/index.php/settings/admin/talk#stun_server`) yes

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

**Comment by SystemKeeper** [comment] 2023-01-16 22:44
Hm... I can't reproduce this right now. Controls are always visible in the correct location. Does this always happen to you?
Regardless of this I guess #997 and #1038 should solve this anyway when released.

**Comment by e-caste** [comment] 2023-01-16 23:17
It happened twice on different days. I can't say that it always happens cause I haven't tested it that many times, but I'm pretty sure it wasn't just a one-off bug

**Comment by SystemKeeper** [comment] 2023-01-16 23:32
I see. Maybe it is related to the bugs we saw before with staying in a conversation. I’ll take a closer look, when I can.

**Comment by andyxheli** [comment] 2023-01-20 18:18
Hey all i also noticed that sometimes when i answer the call the end users video comes up but im missing all menu buttons on the bottom.  Here what is looks like

![2023-01-20 12_09_56-IMG_1674237119686 jpg](https://user-images.githubusercontent.com/59488153/213775344-645b2ac4-f484-4d67-a1b4-d38665bcc0db.png)

**Comment by SystemKeeper** [comment] 2023-01-26 22:09
Quick workaround: rotating the screen should bring back the buttons for now.

**Comment by SystemKeeper** [comment] 2023-03-13 09:11
Since we are approaching Talk 16 quite fast, I'm closing this as this shouldn't be an issue anymore. Feel free to check out the latest Beta version at TestFlight and report any issues.

**Closed as completed by SystemKeeper** 2023-03-13 09:11 UTC
Labels: bug, 0. Needs triage
