### ISSUE TITLE
App dose not open when answring call from locked screen

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/spreed-ios#1052] opened 2023-01-20 17:56 UTC
## Steps to reproduce
1. Someone calls me
2.anwear call from locaked screen
3. nextcloud app dose not open just shows 

### Expected behaviour
Once call is answear should open the nextcloud talk app 

### Actual behaviour
Opens apple calls screen

![23-01-20 11-49-53 0558](https://user-images.githubusercontent.com/59488153/213772567-2b404503-b0a6-40cb-a82d-7f65a7e2ef20.png)

## Device information

**Device:** iPhone X/iPad Y/…
iPhone 13 Pro
**iOS version:** 10/…
16.0.2
**Talk version:** 11.1.1
15.2.5
## Server information

**Nextcloud version:** (see admin overview page: `/index.php/settings/admin/overview`)
25.0.3
**Talk version:** (see apps admin page: `/index.php/settings/apps`)
15.0.3
**Custom Signaling server configured:** yes/no and version (see talk admin settings: `/index.php/settings/admin/talk#signaling_server`)

**Custom TURN server configured:** yes/no (see talk admin settings: `/index.php/settings/admin/talk#turn_server`)
yes
**Custom STUN server configured:** yes/no (see talk admin settings: `/index.php/settings/admin/talk#stun_server`)
yes
### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

**Comment by SystemKeeper** [comment] 2023-01-20 17:58
Duplicate of https://github.com/nextcloud/talk-ios/issues/903

**Comment by AndyXheli** [comment] 2023-01-20 17:59
Thank you! & sorry for the dup

**Closed as completed by SystemKeeper** 2023-01-20 17:58 UTC
Labels: bug, 0. Needs triage
