### ISSUE TITLE
Picture in Picture support

### ISSUE THREAD

**Issue by DenuxPlays** [nextcloud/spreed-ios#1174] opened 2023-03-30 09:45 UTC
**Is your feature request related to a problem? Please describe.**
If I want to still see the person I have a video call with and I want to do some work I have to use two devices.

**Describe the solution you'd like**
If I minimize Nextcloud Talk a small PiP window should pop out (like it is with facetime or WhatsApp).

**Describe alternatives you've considered**
/

**Additional context**
/

**Comment by SystemKeeper** [comment] 2023-04-04 08:36
Duplicate of #364

**Closed as not planned by SystemKeeper** 2023-04-04 08:36 UTC
Labels: enhancement, 0. Needs triage
